export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Terms of Service</h1>

        <div className="prose dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
          <p className="text-sm text-gray-500">Last Updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using AeonForge ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, you should not use this Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">2. Use of Service</h2>
            <p>AeonForge is an AI-powered assistant platform. You agree to use the Service only for lawful purposes and in accordance with these Terms.</p>
            <p className="mt-2"><strong>You agree NOT to use the Service to:</strong></p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Engage in any illegal activities</li>
              <li>Generate content that violates laws or regulations</li>
              <li>Harass, abuse, or harm another person</li>
              <li>Impersonate any person or entity</li>
              <li>Distribute malware or harmful code</li>
              <li>Attempt to gain unauthorized access to the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">3. Medical Disclaimer</h2>
            <div className="bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-500 p-4">
              <p className="font-semibold">IMPORTANT MEDICAL DISCLAIMER:</p>
              <p className="mt-2">
                AeonForge provides AI-generated information that may include health-related content. This information is for educational purposes only and does not constitute medical advice, diagnosis, or treatment.
              </p>
              <p className="mt-2">
                <strong>Always seek the advice of your physician or other qualified health provider</strong> with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay seeking it because of information obtained from AeonForge.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">4. Subscription and Billing</h2>
            <p><strong>Free Tier:</strong> Limited to 10 messages per month.</p>
            <p><strong>Paid Subscriptions:</strong></p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Standard: $15/month - 2M tokens/month, 1GB storage</li>
              <li>Pro: $40/month - Unlimited tokens, 5GB storage</li>
              <li>Team: $20/seat/month (2 seat minimum)</li>
              <li>Enterprise: $18/seat/month (4 seat minimum)</li>
            </ul>
            <p className="mt-2">
              Subscriptions automatically renew unless cancelled. You may cancel at any time. No refunds for partial months.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">5. Content and Intellectual Property</h2>
            <p><strong>Your Content:</strong> You retain ownership of content you input into the Service.</p>
            <p className="mt-2"><strong>AI-Generated Content:</strong> Content generated by AI models is provided "as is". While we strive for accuracy, we make no guarantees about the correctness, completeness, or reliability of generated content.</p>
            <p className="mt-2"><strong>Service Content:</strong> The Service itself, including its design, features, and functionality, is owned by AeonForge and protected by copyright and other intellectual property laws.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">6. Data and Privacy</h2>
            <p>
              We collect and process data as described in our Privacy Policy. By using the Service, you consent to such processing and warrant that all data provided is accurate.
            </p>
            <p className="mt-2">
              <strong>Data Storage:</strong> Your data is stored securely using Supabase. We implement industry-standard security measures to protect your information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">7. Content Moderation</h2>
            <p>
              We employ automated and human content moderation to ensure compliance with these Terms. Content that violates our policies may be flagged, and repeat violations may result in account suspension or termination.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">8. Disclaimers and Limitations of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
            </p>
            <p className="mt-2">
              TO THE FULLEST EXTENT PERMITTED BY LAW, AEONFORGE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">10. Termination</h2>
            <p>
              We may terminate or suspend your account immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">11. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us at:
              <br />
              <a href="mailto:info@stephenscode.dev" className="text-primary-600 hover:underline">
                info@stephenscode.dev
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
